ribbon:
    eureka:
        enabled: false
myuaa:
    ribbon:
        eureka:
            enabled: false
        listOfServers: http://rso_myuaa-app:9999
uaa:
    ribbon:
        eureka:
            enabled: false
        listOfServers: http://rso_myuaa-app:9999
msapp:
    ribbon:
        eureka:
            enabled: false
        listOfServers: http://rso_msapp-app:8081
msrodo:
    ribbon:
        eureka:
            enabled: false
        listOfServers: http://rso_msrodo-app:8082
zuul:
  routes:
      msapp:
          path: /msapp/**
          serviceId: msapp
      msapp:
          path: /msrodo/**
          serviceId: msrodo
      myuaa:
          path: /myuaa/**
          serviceId: myuaa
      uaa:
          path: /myuaa/**
          serviceId: myuaa
