version: "3"
services:   
    mygateway-app:
        image: mygateway
        environment:
            - SPRING_PROFILES_ACTIVE=dev,no-liquibase,zuul,no-eureka
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - JHIPSTER_SLEEP=2
            - JHIPSTER_REGISTRY_PASSWORD=admin
        ports:
            - 8080:8080